[LM-10286] Feed v0.6.0 UI changes
LikeMindsCommunity/LikeMinds-ReactNative-Feed-UI pull request #23
Opened 2023-11-23 11:04 UTC by prabha-likeminds

## Description

**Features**

**Bugs**
- UI changes for post detail feature

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-11-28 11:04 UTC, ishaan1607 requested changes

2023-11-28 11:04 UTC, ishaan1607 commented on src/base/LMButton/index.tsx
> +  clickDisable = false,
rename to `isClickable`

2023-11-28 11:04 UTC, ishaan1607 commented on src/base/LMButton/types.ts
> +  onTap: (value?: any) => void; // this represents the functionality to be executed on click of button
why `any`?

2023-11-28 11:04 UTC, ishaan1607 commented on src/base/LMInputText/index.tsx
> +  }, [autoFocus]);
add comments for this useEffects

2023-11-28 11:04 UTC, ishaan1607 commented on src/base/LMInputText/index.tsx
> +  const textInputRef = useRef<TextInput>(null);
what is the use of this?

2023-11-28 11:04 UTC, ishaan1607 commented on src/base/LMText/types.ts
> +  onTextLayout?: (event?: any) => void; // callback function executed on change of text layout
why `any`?

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +  }, [comment?.isLiked, comment?.likesCount]);
add comments, what is the of this useEffect?

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +  };
add comments for this

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +  };
Give some above this like one new line, also rename to `onOverflowMenuClick()`

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +                        ? (onTapReplies((data: any) => setRepliesArray(data)),
why `any`?

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +            <FlatList
are we using `FlashList` or `FlatList`, please maintain only one.

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +                                      (data: any) => setRepliesArray(data),
why `any`?

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +                                : () => {}
There is a lint error on this line, please check

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/types.ts
> +  onTapViewMore?: (val: any, val2: any) => void; // callback function to be executed on click of view more replies
why `any`? and please use appropriate variable names.

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMCommentItem/types.ts
> +  onTapReplies?: (val: any) => void; // callback function to be executed on click of replies
why `any`?

2023-11-28 11:04 UTC, ishaan1607 commented on src/components/LMPost/LMPostContent/index.tsx
> +    (e: {nativeEvent: {lines: string | TextLayoutLine[]}}) => {
rename `e` to `event`

2023-11-29 07:07 UTC, prabha-likeminds commented on src/base/LMInputText/index.tsx
> +  const textInputRef = useRef<TextInput>(null);
its used to make the textinput focused depending on the prop value

2023-11-29 07:10 UTC, prabha-likeminds commented on src/base/LMButton/types.ts
> +  onTap: (value?: any) => void; // this represents the functionality to be executed on click of button
this is the callback value we get on click of button so it can be anything(string, object, number etc) depending on use case

2023-11-29 07:40 UTC, prabha-likeminds commented on src/components/LMCommentItem/index.tsx
> +            <FlatList
Flashlist is not working properly in nested list of comments, on modifying the list like deleting comment or view replies of comment the list behaves in a weird manner.

2023-11-29 08:21 UTC, ishaan1607 commented on src/base/LMButton/types.ts
> +  onTap: (value?: any) => void; // this represents the functionality to be executed on click of button
Okay

2023-11-29 08:21 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +            <FlatList
Okay

2023-11-29 10:38 UTC, ishaan1607 requested changes

2023-11-29 10:38 UTC, ishaan1607 commented on src/components/LMCommentItem/index.tsx
> +                                : 'View more replies',
add in string constant

2023-12-12 12:10 UTC, ishaan1607 approved these changes

2023-12-12 12:13 UTC, merged