[LM-9622] Added LMProfilePicture
LikeMindsCommunity/LikeMinds-ReactNative-Feed-UI pull request #5
Opened 2023-09-17 15:49 UTC by prabha-likeminds

## Description

**Features**
- Added LMProfilePicture component

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2023-09-17 15:57 UTC, ishaan1607 requested changes

2023-09-17 15:57 UTC, ishaan1607 commented on src/utils/constants.ts
empty file?

2023-09-18 05:46 UTC, prabha-likeminds commented on src/utils/constants.ts
will be used later for defining style constants

2023-09-18 07:56 UTC, ishaan1607 approved these changes

2023-09-18 10:02 UTC, merged