[LM-9624] LMMedia
LikeMindsCommunity/LikeMinds-ReactNative-Feed-UI pull request #7
Opened 2023-09-21 12:30 UTC by prabha-likeminds

## Description

**Features**
- Added LMImage, LMVideo, LMCarousel, LMDocument, LMLinkPreview components

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [x] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [x] Label added
- [x] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [x] Description about the Feature/ Bugs added

2023-09-22 06:06 UTC, ishaan1607 requested changes

2023-09-22 06:06 UTC, ishaan1607 commented on src/base/LMLoader/types.ts
> +export interface LoaderProps {
rename to `LMLoaderProps`

2023-09-22 06:06 UTC, ishaan1607 commented on src/base/LMLoader/index.tsx
> +  return <ActivityIndicator size={size ? size : 'large'} color={color? color : '#5046E5'} />;
we should `#5046E5` to some variable and then use it.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMCarousel/index.tsx
> +        {backgroundColor: '#5046E5'},
we should `#5046E5` to some variable and then use it.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMCarousel/index.tsx
> +        {backgroundColor: '#e0e0e0'},
we should `#e0e0e0` to some variable and then use it.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMCarousel/types.ts
> +  attachments: Array<object>; // this represents the array of image & video attachments to be displayed
this should be `Array<LMAttachmentUI>` and not `object`, these are UI models we are talking about.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/index.tsx
> +                  278 Kb
Why we have added this `278 kb`, if it is a dummy value, please add a todo

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/index.tsx
> +                  2 Pages
Why we have added this `278 kb`, if it is a dummy value, please add a todo

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/index.tsx
> +    // fontFamily: STYLES.$FONT_FAMILY.REGULAR
remove commented code?

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/index.tsx
> +    // fontFamily: STYLES.$FONT_FAMILY.REGULAR
remove commented code

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/types.ts
> +}
move this interface to separate folder and use builder pattern to make these models.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/types.ts
> +interface DocumentItem {
this will LMAttachmentUI

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMDocument/types.ts
> +interface AttachmentMeta {
this will be LMAttachmentMetaUI

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMImage/index.tsx
> +              An error occured while fetching the media
move this string to constant file.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMLinkPreview/index.tsx
> +        Linking.openURL(attachments?.attachmentMeta?.ogTags?.url), onTap;
assign `attachments?.attachmentMeta?.ogTags` to a variable and the use this.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMLinkPreview/types.ts
> +}
move this interface to different folder, and then use it here and use builder pattern for creating this class.

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMLinkPreview/types.ts
> +interface OgTagsProps {
this will be LMOGTagsUI

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMLinkPreview/types.ts
> +interface AttachmentMeta {
repeated class

2023-09-22 06:06 UTC, ishaan1607 commented on src/components/LMMedia/LMVideo/index.tsx
> +              An error occured while fetching the media
move this string to a constant and then use it.

2023-09-27 10:16 UTC, ishaan1607 approved these changes

2023-09-29 09:33 UTC, divyanshgandhilm approved these changes

2023-09-29 17:09 UTC, merged